apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: TLSRoute
    namespace: {{ .Values.system.namespace }}
  to:
  - group: ""
    kind: Service