apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cni
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cni
      version: 1.25.0
      sourceRef:
        kind: HelmRepository
        name: istio-repo
        namespace: flux-system
  interval: 5m
  releaseName: cni
  dependsOn:
    - name: base
  targetNamespace: istio-system 
  install:
    createNamespace: true
  values:
    profile: ambient