apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base
      version: 1.25.0
      sourceRef:
        kind: HelmRepository
        name: istio-repo
        namespace: flux-system
  interval: 5m
  releaseName: base
  targetNamespace: istio-system
  install:
    createNamespace: true
  values:
    # Add any custom values here
