apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: istiod
      version: 1.25.0
      sourceRef:
        kind: HelmRepository
        name: istio-repo
        namespace: flux-system
  interval: 5m
  releaseName: istiod
  dependsOn:
    - name: cni
  targetNamespace: istio-system
  install:
    createNamespace: true
  values:
    profile: ambient
    env:
      PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
    global:
      defaultPodDisruptionBudget:
        enabled: false