apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: tenant-ocirepo
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/kubespaces-io/kubespaces-public/tenant
  ref:
    semver: "0.1.6"