---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tenant-helmrepo
  namespace: flux-system
spec:
  interval: 5m
  type: oci
  url: oci://ghcr.io/kubespaces-io/kubespaces-public/tenant