#tenant: dev, org: contoso, domain: kubespaces.cloud
apiVersion: v1
kind: Namespace
metadata:
  name: dev-contoso
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-contoso-values
  namespace: dev-contoso
data:
  values.yaml: |
    tenant:
      location_short: ne
      cloud: azure
      tenant: dev
      org: contoso
      domain: kubespaces.cloud
    vcluster:
      exportKubeConfig:
        server: https://api.dev.contoso.ne.azure.kubespaces.cloud
      controlPlane:
        proxy:
          extraSANs:
            - api.dev.contoso.ne.azure.kubespaces.cloud