apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dev-contoso-tenant
  namespace: dev-contoso
spec:
  interval: 10m
  timeout: 5m
  releaseName: dev-contoso
  chartRef:
    kind: OCIRepository
    name: tenant-ocirepo
    namespace: flux-system
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: dev-contoso-values # noqa: contoso
      valuesKey: values.yaml