apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-issuers-values
  namespace: cert-manager
data:
  values.yaml: |
    _: &email alessandro.vozza@linux.com
    _: &solvers
    - http01:
        ingress:
          class: nginx

    clusterIssuers:
    - name: letsencrypt-prod
      spec:
        acme:
          email: *email
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-prod-account-key
          solvers: *solvers
