apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contoso-dev
  namespace: contoso-dev
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: tenant
      version: 0.1.3
      sourceRef:
        kind: OCIRepository
        name: tenant-helmrepo
        namespace: flux-system
      interval: 5m
  releaseName: contoso-dev
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: contoso-dev-values
      valuesKey: values.yaml
